"use client";
import { useMemo, useState } from "react";
import { useProfile } from "@/components/shared/user-profile-provider";
import { consistency, dateKey, detectRecords, formatWeight, fromDisplayWeight, oneRepMaxes, toDisplayWeight, weekStartDate, weightUnit } from "@/features/training/logic";
import { LineChart } from "./line-chart";
import type { WorkoutRecord } from "@/features/workouts/model";
import type { PhysiqueEntry } from "@/features/physique/model";

export default function AdvancedAnalytics({workouts,entries}:{workouts:WorkoutRecord[];entries:PhysiqueEntry[]}){
  const {user,preferences,save}=useProfile();const units=preferences.units;
  const stats=consistency(workouts,new Date(),preferences.weekStart);
  const records=useMemo(()=>detectRecords(workouts),[workouts]);const [recordType,setRecordType]=useState("all"),[limit,setLimit]=useState(30);
  const [weight,setWeight]=useState(""),[reps,setReps]=useState(5);
  const estimate=oneRepMaxes(fromDisplayWeight(Number(weight),units),reps);
  const [date,setDate]=useState(dateKey(new Date())),[bodyWeight,setBodyWeight]=useState(""),[fat,setFat]=useState("");const [message,setMessage]=useState("");
  const metrics=[...(user?.profile.bodyMetricsHistory??[]),...entries.filter(e=>e.kind==="bodyweight").map(e=>({id:e.id,date:dateKey(new Date(e.measuredAt)),weight:e.value,bodyFat:null}))].sort((a,b)=>a.date.localeCompare(b.date));
  const cutoff=new Date();cutoff.setDate(cutoff.getDate()-30);
  const recent=metrics.filter(m=>m.date>=dateKey(cutoff));const change=recent.length>1?recent[recent.length-1].weight-recent[0].weight:null;
  const daily=new Map<string,number>();for(const workout of workouts){const key=dateKey(new Date(workout.completedAt??workout.startedAt));daily.set(key,(daily.get(key)??0)+workout.exercises.flatMap(e=>e.sets).filter(s=>s.completed&&s.setType!=="warmup").reduce((sum,s)=>sum+(s.weight??0)*(s.reps??0),0));}
  const heat=Array.from({length:182},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(181-i));const key=dateKey(d);return {key,value:daily.get(key)??0,trained:daily.has(key)};});
  const maxVolume=Math.max(...heat.map(h=>h.value),1);
  const muscles=[...new Set(workouts.flatMap(w=>w.exercises.map(e=>e.muscle)))].sort();const [muscle,setMuscle]=useState("all");
  const weeks=Array.from({length:12},(_,i)=>{const start=weekStartDate(new Date(),preferences.weekStart);start.setDate(start.getDate()-(11-i)*7);return {start,label:start.toLocaleDateString(undefined,{month:"short",day:"numeric"}),sets:0};});
  for(const workout of workouts){const key=dateKey(weekStartDate(new Date(workout.completedAt??workout.startedAt),preferences.weekStart));const week=weeks.find(w=>dateKey(w.start)===key);if(week)week.sets+=workout.exercises.filter(e=>muscle==="all"||e.muscle===muscle).flatMap(e=>e.sets).filter(s=>s.completed&&s.setType!=="warmup").length;}
  const maxSets=Math.max(...weeks.map(w=>w.sets),1);
  async function addMetric(event:React.FormEvent){event.preventDefault();if(!user){setMessage("Sign in to save body metrics.");return;}const kg=fromDisplayWeight(Number(bodyWeight),units),bodyFat=fat===""?null:Number(fat);if(kg<20||kg>500||bodyFat!==null&&(bodyFat<0||bodyFat>60)){setMessage("Check your weight and body fat values.");return;}const snapshot={id:crypto.randomUUID(),date,weight:kg,bodyFat};const history=[...(user.profile.bodyMetricsHistory??[]),snapshot].sort((a,b)=>a.date.localeCompare(b.date));await save({...user.profile,bodyMetricsHistory:history.slice(-1500),bodyMetrics:history[history.length-1]?{weight:history[history.length-1].weight,bodyFat:history[history.length-1].bodyFat}:user.profile.bodyMetrics});setMessage("Dated measurement saved and queued for sync.");setBodyWeight("");setFat("");}
  return <>
    <section className="feature-panel"><div className="panel-heading"><div><p className="eyebrow">SHOWING UP COUNTS</p><h2>Consistency</h2></div></div><div className="consistency-overview"><svg viewBox="0 0 100 100" className="consistency-ring" role="img" aria-label={`${stats.lastSeven} of the last 7 days trained`}><circle cx="50" cy="50" r="40" fill="none" stroke="var(--line)" strokeWidth="8"/><circle cx="50" cy="50" r="40" fill="none" stroke="#3b82f6" strokeWidth="8" strokeDasharray={`${stats.lastSeven/7*251.33} 251.33`} transform="rotate(-90 50 50)"/><text x="50" y="55" textAnchor="middle" fill="var(--ink)" fontSize="20">{stats.lastSeven}/7</text></svg><div><strong>{stats.streak} day streak</strong><p>You trained {stats.lastSeven} out of the last 7 days.</p><small className="feature-muted">{stats.weeklyStreak} consecutive training weeks · week starts {preferences.weekStart}</small></div></div><div className="training-heatmap" role="img" aria-label="Training volume by day for the last six months">{heat.map(h=><span key={h.key} title={`${h.key}: ${h.trained?formatWeight(h.value,units):"Rest day"}`} style={{background:h.trained?(h.value/maxVolume>.5?"#22c55e":"#14532d"):"var(--line)"}}/>)}</div><p className="feature-muted">Last 6 months · brighter green means more volume</p></section>
    <section className="feature-panel"><div className="panel-heading"><h2>Weekly working sets</h2><select aria-label="Weekly sets muscle group" value={muscle} onChange={e=>setMuscle(e.target.value)}><option value="all">All muscles</option>{muscles.map(m=><option key={m}>{m}</option>)}</select></div><svg className="weekly-sets-chart" viewBox="0 0 640 200" role="img" aria-label={`Working sets per week for ${muscle}`}><line x1="20" y1="175" x2="630" y2="175" stroke="var(--line)"/>{weeks.map((w,i)=><g key={i}><rect x={25+i*50} y={175-w.sets/maxSets*145} width="32" height={w.sets/maxSets*145} rx="3" fill="#3b82f6"><title>{w.label}: {w.sets} working sets</title></rect><text x={41+i*50} y="195" fill="var(--muted)" fontSize="8" textAnchor="middle">{w.label}</text><text x={41+i*50} y={170-w.sets/maxSets*145} fill="var(--ink)" fontSize="10" textAnchor="middle">{w.sets}</text></g>)}</svg><small className="feature-muted">Attributed to the logged exercise’s primary muscle; warm-ups excluded.</small></section>
    <section className="feature-panel"><h2>Body composition</h2>{change!==null&&<p>{change<0?"↓":"↑"} {formatWeight(Math.abs(change),units)} across measurements in the last 30 days</p>}<LineChart label={`Bodyweight · ${weightUnit(units)}`} secondaryLabel="Body fat %" points={metrics.slice(-60).map(m=>({label:m.date,value:toDisplayWeight(m.weight,units),secondary:m.bodyFat}))}/><form className="feature-grid metric-form" onSubmit={e=>void addMetric(e)}><label>Date<input type="date" required max={dateKey(new Date())} value={date} onChange={e=>setDate(e.target.value)}/></label><label>Weight · {weightUnit(units)}<input type="number" step="0.1" required value={bodyWeight} onChange={e=>setBodyWeight(e.target.value)}/></label><label>Body fat · % (optional)<input type="number" min="0" max="60" step="0.1" value={fat} onChange={e=>setFat(e.target.value)}/></label><button className="outline-button" disabled={!user}>Add measurement</button></form>{message&&<p role="status">{message}</p>}</section>
    <section className="feature-panel"><h2>1RM calculator</h2><p className="feature-muted">Compare three estimates from a set of 1–12 reps.</p><div className="feature-grid"><label>Load · {weightUnit(units)}<input type="number" min="0" step="0.5" value={weight} onChange={e=>setWeight(e.target.value)}/></label><label>Reps<input type="number" min="1" max="12" value={reps} onChange={e=>setReps(Number(e.target.value))}/></label></div>{estimate&&<><div className="calculator-results">{Object.entries(estimate).map(([name,value])=><div key={name}><span>{name}</span><strong>{formatWeight(value,units)}</strong></div>)}</div><div className="calculator-percentages">{[[5,.87],[8,.8],[10,.75],[12,.7]].map(([rm,percent])=><p key={rm}>{rm}RM · ~{percent*100}% <strong>{formatWeight(estimate.average*percent,units)}</strong></p>)}</div></>}</section>
    <section className="feature-panel"><div className="panel-heading"><h2>PR timeline</h2><select aria-label="Record type" value={recordType} onChange={e=>{setRecordType(e.target.value);setLimit(30);}}><option value="all">All records</option><option value="1rm">Heaviest single</option><option value="estimated_1rm">Estimated 1RM</option><option value="volume">Session volume</option></select></div>{records.filter(r=>recordType==="all"||r.type===recordType).slice(0,limit).map(r=><article className="pr-row" key={r.id}><div><strong>{r.exerciseName}</strong><small>{new Date(r.date).toLocaleDateString()} · {r.type==="1rm"?"Single rep":r.type==="volume"?"Session volume":"Estimated 1RM"}</small></div><strong>{formatWeight(r.value,units)}</strong></article>)}{records.length===0&&<p className="feature-muted">Complete weighted sets to build your PR timeline.</p>}{records.filter(r=>recordType==="all"||r.type===recordType).length>limit&&<button className="text-action" onClick={()=>setLimit(limit+30)}>Show more records</button>}</section>
  </>;
}
