"use client";
export type ChartPoint={label:string;value:number;secondary?:number|null};
export function LineChart({points,label,secondaryLabel}:{points:ChartPoint[];label:string;secondaryLabel?:string}){
  if(!points.length)return <p className="feature-muted">Log data to build this chart.</p>;
  const values=points.map(p=>p.value),min=Math.min(...values),max=Math.max(...values),range=max-min||1;
  const x=(i:number)=>40+(points.length===1?280:i*560/(points.length-1));const y=(v:number)=>165-(v-min)/range*135;
  const secondary=points.map(p=>p.secondary).filter((v):v is number=>typeof v==="number");const secondMin=Math.min(...secondary),secondMax=Math.max(...secondary),secondRange=secondMax-secondMin||1;
  return <figure className="feature-chart"><svg viewBox="0 0 640 205" role="img" aria-label={label}><title>{label}</title>{[0,1,2,3].map(i=><g key={i}><line x1="40" x2="600" y1={30+i*45} y2={30+i*45} stroke="var(--line)"/><text x="3" y={34+i*45} fill="var(--muted)" fontSize="10">{(max-i*(max-min)/3).toFixed(1)}</text></g>)}<polyline points={points.map((p,i)=>`${x(i)},${y(p.value)}`).join(' ')} fill="none" stroke="#3b82f6" strokeWidth="3"/>{points.map((p,i)=><circle key={i} cx={x(i)} cy={y(p.value)} r="3" fill="#3b82f6"><title>{p.label}: {p.value.toFixed(1)}</title></circle>)}{secondaryLabel&&points.flatMap((p,i)=>typeof p.secondary==="number"?[<circle key={i} cx={x(i)} cy={165-(p.secondary-secondMin)/secondRange*135} r="3" fill="#f59e0b"><title>{p.label}: {p.secondary}% body fat</title></circle>]:[])}{secondaryLabel&&secondary.length>0&&<><text x="605" y="35" fill="#f59e0b" fontSize="10">{secondMax}%</text><text x="605" y="165" fill="#f59e0b" fontSize="10">{secondMin}%</text></>}{points.filter((_,i)=>i===0||i===points.length-1||i===Math.floor(points.length/2)).map((p,i)=><text key={`${p.label}-${i}`} x={x(points.indexOf(p))} y="195" textAnchor="middle" fill="var(--muted)" fontSize="10">{p.label}</text>)}</svg><figcaption>{label}{secondaryLabel&&secondary.length>0?` · amber dots: ${secondaryLabel} (right axis)`:""}</figcaption><details><summary>View chart data</summary><table className="feature-table"><thead><tr><th>Date</th><th>Value</th>{secondaryLabel&&<th>{secondaryLabel}</th>}</tr></thead><tbody>{points.map((p,i)=><tr key={i}><td>{p.label}</td><td>{p.value.toFixed(1)}</td>{secondaryLabel&&<td>{p.secondary??"—"}</td>}</tr>)}</tbody></table></details></figure>;
}
