"use client";
import { useEffect, useState } from "react";
import { listExerciseSettings, saveExerciseSettings } from "@/features/local-data/repository";
import { useProfile } from "@/components/shared/user-profile-provider";
import { fromDisplayWeight, toDisplayWeight, weightUnit } from "@/features/training/logic";
import type { ProgressionRule } from "@/features/profile/model";
import { exerciseSettingsSchema } from "@/features/import-export/restore-schema";
export function ExerciseSettingsPanel({id}:{id:string}){
  const {preferences}=useProfile();const [rest,setRest]=useState<number|undefined>(undefined);
  const [rule,setRule]=useState<ProgressionRule>({type:"none",increment:2.5,repMin:8,repMax:12,deloadPercent:10,deloadAfterFails:3});const [message,setMessage]=useState("");
  useEffect(()=>{void listExerciseSettings().then(items=>{const item=items.find(s=>s.id===id);setRest(item?.restSeconds);if(item?.progression)setRule(item.progression);else setRule({type:"none",increment:preferences.units==="imperial"?fromDisplayWeight(5,"imperial"):2.5,repMin:8,repMax:12,deloadPercent:10,deloadAfterFails:3});}).catch(()=>setMessage("Could not load exercise settings."));},[id,preferences.units]);
  async function save(){const value={id,restSeconds:rest,progression:rule,updatedAt:new Date().toISOString(),syncStatus:"pending" as const};const parsed=exerciseSettingsSchema.safeParse(value);if(!parsed.success){setMessage(parsed.error.issues[0]?.message??"Check your exercise settings.");return;}try{await saveExerciseSettings(value);setMessage("Settings saved. They apply when this exercise is added to a new workout.");}catch{setMessage("Could not save locally. Please retry.");}}
  return <section className="feature-panel"><h2>Rest & progression</h2><div className="feature-grid"><label>Rest override · seconds<input type="number" min="0" max="1800" value={rest??""} placeholder={`Profile default (${preferences.defaultRestTimer}s)`} onChange={e=>setRest(e.target.value===""?undefined:Math.max(0,Math.min(1800,Number(e.target.value))))}/></label><label>Progression<select value={rule.type} onChange={e=>setRule({...rule,type:e.target.value as ProgressionRule["type"]})}><option value="none">Manual</option><option value="linear">Linear · add load at target reps</option><option value="double">Double · build reps then load</option></select></label><label>Increment · {weightUnit(preferences.units)}<input type="number" min="0.1" step="0.1" value={Number(toDisplayWeight(rule.increment,preferences.units).toFixed(2))} onChange={e=>setRule({...rule,increment:fromDisplayWeight(Number(e.target.value),preferences.units)})}/></label><label>Lower / target reps<input type="number" min="1" max="100" value={rule.repMin} onChange={e=>setRule({...rule,repMin:Number(e.target.value)})}/></label><label>Upper rep range<input type="number" min="1" max="100" value={rule.repMax} onChange={e=>setRule({...rule,repMax:Number(e.target.value)})}/></label><label>Deload after missed sessions<input type="number" min="0" max="10" value={rule.deloadAfterFails} onChange={e=>setRule({...rule,deloadAfterFails:Number(e.target.value)})}/></label><label>Deload reduction · %<input type="number" min="0" max="60" value={rule.deloadPercent} onChange={e=>setRule({...rule,deloadPercent:Number(e.target.value)})}/></label></div><button className="outline-button" onClick={()=>void save()}>Save exercise settings</button>{message&&<p role="status">{message}</p>}</section>;
}
