"use client";
import { usePageTitle } from "@/components/shared/page-title";
import { NumericInput } from "@/components/shared/numeric-input";
import { useEffect,useState } from "react";
import { useLocalRouteId } from "@/components/shared/use-local-route-id";
import Link from "next/link";
import { listPrograms,saveProgram } from "@/features/local-data/repository";
import { useProfile } from "@/components/shared/user-profile-provider";
import type { TrainingProgram } from "@/features/programs/model";
import { programSchedule } from "@/features/programs/schedule";
import { dateKey,fromDisplayWeight,toDisplayWeight,weightUnit } from "@/features/training/logic";
export default function ProgramDetail(){const id=useLocalRouteId();const {user,save,preferences}=useProfile();const [program,setProgram]=useState<TrainingProgram|null>(null),[date,setDate]=useState(dateKey(new Date())),[message,setMessage]=useState("");const [maxes,setMaxes]=useState<Record<string,number>>({});
 usePageTitle(program?.name ?? "Program");
 useEffect(()=>{void listPrograms().then(items=>setProgram(items.find(p=>p.id===id)??null)).catch(()=>setMessage("Could not load this program."));},[id]);
 async function enroll(){if(!user){setMessage("Sign in to keep your enrollment.");return;}await save({...user.profile,activeProgram:{programId:id,startDate:date,trainingMaxes:maxes}});setMessage("Program started. Your dashboard now shows the schedule.");}
 async function update(change:Partial<TrainingProgram>){if(!program)return;const next={...program,...change,updatedAt:new Date().toISOString(),syncStatus:"pending" as const};await saveProgram(next);setProgram(next);}
 if(!program)return <main className="workout-shell"><Link className="back-link" href="/programs">← Programs</Link><p>{message||"Loading program…"}</p></main>;
 const enrolled=user?.profile.activeProgram?.programId===id?user.profile.activeProgram:null;
 const schedule=enrolled?programSchedule(program,enrolled):null;
 const percentageLifts=[...new Map(program.days.flatMap(d=>d.exercises.filter(e=>e.setTargets?.some(s=>s.percentage)).map(e=>[e.exerciseId,e.name] as const))).entries()];
 return <main className="workout-shell"><header className="workout-top"><Link className="back-link" href="/programs">← Programs</Link><Link className="back-link" href="/dashboard">Home</Link></header><section className="history-heading"><p className="eyebrow">YOUR TRAINING PLAN</p><h1>{program.name}</h1><p>{program.description??program.goal}</p></section>{schedule&&<section className="feature-panel"><h2>{schedule.finished?"Program complete":`Week ${schedule.week} of ${schedule.totalWeeks} · Block ${schedule.block}`}</h2><p>{schedule.deload?"Deload week · reduced volume and load":schedule.deloadNext?"Deload next week":"Build steadily this week"}</p>{schedule.day?<Link className="action-button" href={`/workout?program=${id}&day=${schedule.day.id}`}>Start {schedule.day.name}</Link>:<p>{schedule.started?"Recovery day":"Your program starts on "+enrolled?.startDate}</p>}<button className="text-action" onClick={()=>user&&void save({...user.profile,activeProgram:null})}>End enrollment</button></section>}
 <section className="feature-panel"><h2>{enrolled?"Restart / update start date":"Start program"}</h2><label>Start date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label>{percentageLifts.length>0&&<><p>Enter a conservative training max for percentage-based sets.</p><div className="feature-grid">{percentageLifts.map(([exerciseId,name])=><label key={exerciseId}>{name} · {weightUnit(preferences.units)}<NumericInput min="1" step="0.5" value={maxes[exerciseId]?Number(toDisplayWeight(maxes[exerciseId],preferences.units).toFixed(1)):""} onChange={e=>setMaxes({...maxes,[exerciseId]:fromDisplayWeight(Number(e.target.value),preferences.units)})}/></label>)}</div></>}<button className="action-button" disabled={!date||percentageLifts.some(([exerciseId])=>!(maxes[exerciseId]>0))} onClick={()=>void enroll()}>Start program</button>{message&&<p role="status">{message}</p>}</section>
 <section className="feature-panel"><h2>Blocks & deloads</h2><div className="feature-grid"><label>Duration · weeks<NumericInput min="1" max="52" value={program.durationWeeks??12} onChange={e=>void update({durationWeeks:Math.max(1,Math.min(52,Number(e.target.value)))})}/></label><label>Block length · weeks<NumericInput min="3" max="5" value={program.blockWeeks??4} onChange={e=>void update({blockWeeks:Math.max(3,Math.min(5,Number(e.target.value)))})}/></label><label>Deload every N weeks · 0 disables<NumericInput min="0" max="12" value={program.deloadEveryNWeeks??4} onChange={e=>void update({deloadEveryNWeeks:Math.max(0,Math.min(12,Number(e.target.value)))})}/></label><label>Deload reduction · %<NumericInput min="0" max="60" value={program.deloadReductionPercent??40} onChange={e=>void update({deloadReductionPercent:Math.max(0,Math.min(60,Number(e.target.value)))})}/></label><label>Training-max increase per block · %<NumericInput min="0" max="10" step="0.5" value={program.blockIncreasePercent??2} onChange={e=>void update({blockIncreasePercent:Math.max(0,Math.min(10,Number(e.target.value)))})}/></label></div></section>
 {Array.from({length:Math.max(1,...program.days.map(d=>d.weekIndex+1))},(_,week)=><section className="feature-panel" key={week}><h2>Template week {week+1}</h2>{program.days.filter(d=>d.weekIndex===week).map(day=><article className="program-schedule-day" key={day.id}><h3>{day.name}</h3>{day.exercises.map(e=><p key={e.id}><strong>{e.name}</strong><span>{e.setTargets?e.setTargets.map(s=>`${s.reps} reps @ ${s.percentage}% TM`).join(" · "):`${e.sets} × ${e.repMin}${e.repMax!==e.repMin?"–"+e.repMax:""}`}{e.targetRpe?` · RPE ${e.targetRpe}`:""}</span></p>)}<Link className="text-action" href={`/workout?program=${id}&day=${day.id}`}>Start this day →</Link></article>)}</section>)}
 </main>;
}
