"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { useProfile } from "@/components/shared/user-profile-provider";
import { generateRecaps } from "@/features/analytics/recaps";
import { listRecaps } from "@/features/local-data/repository";
import type { WeeklyRecap } from "@/features/profile/model";
import { formatWeight } from "@/features/training/logic";
export default function RecapsPage(){const {preferences}=useProfile();const [recaps,setRecaps]=useState<WeeklyRecap[]>([]),[message,setMessage]=useState("");useEffect(()=>{void generateRecaps(preferences).then(()=>listRecaps()).then(rows=>setRecaps(rows.sort((a,b)=>b.start.localeCompare(a.start)))).catch(()=>setMessage("Could not load recaps."));},[preferences]);async function enable(){if(!("Notification" in window)){setMessage("Notifications are unavailable in this browser. Recaps still appear here.");return;}const permission=await Notification.requestPermission();localStorage.setItem("arcus-recap-alerts",permission==="granted"?"enabled":"disabled");setMessage(permission==="granted"?"Recap alerts enabled when ARCUS opens after a week finishes.":"Recaps remain available here.");}return <main className="workout-shell"><header className="workout-top"><Link className="back-link" href="/dashboard">← Home</Link></header><section className="history-heading"><p className="eyebrow">YOUR WEEK, MEASURED</p><h1>Weekly recaps.</h1><p>Completed weeks are saved locally. Your week ends {preferences.weekStart==="monday"?"Sunday":"Saturday"}.</p></section><button className="outline-button" onClick={()=>void enable()}>Enable recap alerts</button><p className="feature-muted">Alerts are created when you open the app after a completed week. Scheduled push delivery needs a push service.</p>{message&&<p role="status">{message}</p>}{recaps.map(r=><section className="feature-panel recap-card" key={r.id}><p className="eyebrow">{r.start} — {r.end}</p><h2>{r.sessions} sessions. A week of progress.</h2><div className="feature-stat-row"><span>{formatWeight(r.volume,preferences.units)} lifted</span><span>{r.records} PRs</span><span>{r.streak} day streak at week end</span></div><Link className="text-action" href="/history">Revisit your sessions →</Link></section>)}{!recaps.length&&<p className="feature-panel">Your first recap appears after a week with completed workouts ends.</p>}</main>;}
