import { z } from "zod";
import { profileDetailsSchema } from "../profile/schema.ts";
import { MAX_WORKOUT_MEDIA, MAX_WORKOUT_MEDIA_DATA_LENGTH, WORKOUT_MEDIA_MIME_TYPES } from "../workouts/model.ts";
const id=z.string().min(1).max(100);
const load=z.number().min(0).max(2000).nullable();
const set=z.object({id,index:z.number().int().nonnegative(),weight:load,reps:z.number().int().min(0).max(10000).nullable(),rpe:z.number().min(0).max(10).nullable(),rir:z.number().min(0).max(5).nullable().optional(),distanceKm:z.number().min(0).max(10000).nullable().optional(),durationSeconds:z.number().int().min(0).max(86400).nullable().optional(),completed:z.boolean(),completedAt:z.string().nullable(),setType:z.enum(["working","warmup","drop","failure","assisted","paused","amrap"]).optional()}).passthrough();
const workoutExercise=z.object({id,exerciseId:id,name:z.string().min(1).max(200),muscle:z.string().max(100),equipment:z.string().max(100),restSeconds:z.number().min(0).max(1800),notes:z.string().max(4000).optional(),trackingType:z.enum(["strength","cardio"]).optional(),sets:z.array(set).max(300),groupId:id.optional()}).passthrough();
export const workoutMediaSchema=z.object({
 id,type:z.enum(["image","video"]),name:z.string().min(1).max(200),mimeType:z.enum(WORKOUT_MEDIA_MIME_TYPES),dataUrl:z.string().max(MAX_WORKOUT_MEDIA_DATA_LENGTH),
}).refine(media=>media.mimeType.startsWith(`${media.type}/`),"Media type must match its file format.")
 .refine(media=>media.dataUrl.startsWith(`data:${media.mimeType};base64,`)&&/^data:[^;,]+;base64,[A-Za-z0-9+/]+={0,2}$/.test(media.dataUrl),"Choose a supported image or video file.");
export const workoutSchema=z.object({id,name:z.string().max(200),startedAt:z.string().datetime(),completedAt:z.string().datetime().nullable(),status:z.enum(["active","completed"]),exercises:z.array(workoutExercise).max(200),notes:z.string().max(20000),location:z.string().max(200).optional(),media:z.array(workoutMediaSchema).max(MAX_WORKOUT_MEDIA,"Attach up to 3 photos or videos.").refine(media=>media.reduce((length,item)=>length+item.dataUrl.length,0)<=MAX_WORKOUT_MEDIA_DATA_LENGTH,"Attached media is too large. Choose smaller files.").optional(),restUntil:z.string().nullable(),updatedAt:z.string().datetime(),tags:z.array(z.string().max(100)).max(20).optional()}).passthrough();
const workout=workoutSchema;
const exercise=z.object({id,name:z.string().min(1).max(200),muscle:z.string().max(100),equipment:z.string().max(100),pattern:z.string().max(100),aliases:z.array(z.string().max(200)).max(50),restSeconds:z.number().min(0).max(1800),primaryMuscles:z.array(z.string().max(100)).max(30).optional(),secondaryMuscles:z.array(z.string().max(100)).max(30).optional(),instructions:z.string().max(10000).optional(),category:z.string().max(100).optional(),videoUrl:z.string().max(2000).refine(url=>url.startsWith("/")||/^https?:\/\//.test(url)).optional(),isCustom:z.boolean().optional(),deleted:z.boolean().optional()}).passthrough();
const programExercise=z.object({id,exerciseId:id,name:z.string().min(1).max(200),muscle:z.string().max(100),equipment:z.string().max(100),sets:z.number().int().min(1).max(20),repMin:z.number().int().min(1).max(100),repMax:z.number().int().min(1).max(100),restSeconds:z.number().min(0).max(1800),progressionMethod:z.enum(["manual","double_progression","rpe","percentage"]),progressionValue:z.number().nullable(),targetRpe:z.number().min(1).max(10).optional(),setTargets:z.array(z.object({reps:z.number().int().min(1).max(100),percentage:z.number().positive().max(200).optional(),rpe:z.number().min(1).max(10).optional()})).max(20).optional()}).passthrough().refine(e=>e.repMax>=e.repMin);
const program=z.object({id,name:z.string().min(1).max(200),goal:z.string().max(200),days:z.array(z.object({id,name:z.string().max(100),weekIndex:z.number().int().min(0).max(52),exercises:z.array(programExercise).max(100)})).max(365),createdAt:z.string().datetime(),updatedAt:z.string().datetime(),description:z.string().max(10000).optional(),level:z.enum(["beginner","intermediate","advanced"]).optional(),daysPerWeek:z.number().int().min(1).max(7).optional(),durationWeeks:z.number().int().min(1).max(52).optional(),blockWeeks:z.number().int().min(3).max(5).optional(),blockIncreasePercent:z.number().min(0).max(10).optional(),deloadEveryNWeeks:z.number().int().min(0).max(12).optional(),deloadReductionPercent:z.number().min(0).max(60).optional(),deleted:z.boolean().optional(),isCustom:z.boolean().optional()}).passthrough();
const physique=z.object({id,kind:z.enum(["bodyweight","measurement"]),metric:z.string().max(100),value:z.number().positive().max(500),unit:z.enum(["kg","cm"]),measuredAt:z.string().datetime(),notes:z.string().max(4000)}).passthrough();
const profile=profileDetailsSchema.extend({experience:z.string().nullable(),goals:z.array(z.string()).max(50),height_cm:z.number().nullable(),bio:z.string().nullable().optional(),avatarUrl:z.string().max(750000).nullable().optional(),age:z.number().nullable().optional(),sex:z.string().nullable().optional()}).passthrough();
export const exerciseSettingsSchema=z.object({id,updatedAt:z.string().datetime(),restSeconds:z.number().int().min(0).max(1800).optional(),progression:z.object({type:z.enum(["none","linear","double"]),increment:z.number().positive().max(100),repMin:z.number().int().min(1).max(100),repMax:z.number().int().min(1).max(100),deloadPercent:z.number().min(0).max(60),deloadAfterFails:z.number().int().min(0).max(10)}).refine(r=>r.repMax>=r.repMin,"Upper reps must be at least lower reps.").optional()}).passthrough();
export const recapSchema=z.object({id,start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),end:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),sessions:z.number().int().nonnegative(),volume:z.number().nonnegative(),records:z.number().int().nonnegative(),streak:z.number().int().nonnegative(),updatedAt:z.string().datetime()}).passthrough();
export const favoriteSchema=z.object({id,favorite:z.boolean(),useCount:z.number().int().nonnegative(),usedAt:z.string().datetime().nullable(),updatedAt:z.string().datetime().optional()}).passthrough();
export const libraryEntrySchema=z.discriminatedUnion("kind",[
 z.object({kind:z.literal("program"),payload:program}),z.object({kind:z.literal("measurement"),payload:physique}),z.object({kind:z.literal("exercise"),payload:exercise}),z.object({kind:z.literal("settings"),payload:exerciseSettingsSchema}),z.object({kind:z.literal("recap"),payload:recapSchema}),z.object({kind:z.literal("favorite"),payload:favoriteSchema}),
]).and(z.object({id,updatedAt:z.string().datetime()})).refine(e=>e.id===e.payload.id,"Record IDs must match.");
export const backupSchema=z.object({
 arcus:z.union([z.literal(2),z.literal(3)]),profile:z.object({id,profile}).passthrough().nullable().optional(),
 workouts:z.array(workout).max(10000),activeWorkout:workout.nullable().optional(),programs:z.array(program).max(500),
 physique:z.array(physique).max(20000),customExercises:z.array(exercise).max(3000),exercises:z.array(exercise).max(5000).optional(),
 exerciseSettings:z.array(exerciseSettingsSchema).max(3000).optional(),recaps:z.array(recapSchema).max(1000).optional(),
 preferences:z.array(favoriteSchema).max(5000).optional(),devicePreferences:profileDetailsSchema.shape.preferences.optional()
});
export function parseBackup(text:string){if(text.length>20*1024*1024)throw new Error("Backup exceeds the 20 MB limit.");let value:unknown;try{value=JSON.parse(text);}catch{throw new Error("Choose a valid ARCUS JSON backup.");}const result=backupSchema.safeParse(value);if(!result.success)throw new Error(`Backup validation failed: ${result.error.issues[0]?.path.join('.')??"data"}. ${result.error.issues[0]?.message??"Invalid data."}`);return result.data;}
