"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";

export function ForgotPasswordForm() {
  const [email, setEmail] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); try { const response = await fetch("/api/auth/forgot-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const data = await response.json() as { message?: string; error?: string }; if (!response.ok) throw new Error(data.error ?? "Could not request a reset link."); setMessage(data.message ?? "If an account matches, a reset link will be sent."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not request a reset link."); } finally { setBusy(false); } }
  return <main className="auth-shell"><section className="auth-card"><p className="eyebrow"><span className="live-dot"/> ACCOUNT RECOVERY</p><h1>Reset your<br/><span>password.</span></h1><p className="auth-intro">We’ll email a one-time reset link. It expires after 15 minutes.</p><form className="auth-form" onSubmit={(event) => void submit(event)}><label>Account email<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} required/></label><button className="action-button auth-submit" disabled={busy}>{busy ? "Sending…" : "Send reset link"}</button></form>{message && <p className="auth-notice" role="status">{message}</p>}{error && <p className="auth-error" role="alert">{error}</p>}<p className="auth-switch"><Link href="/login">Return to sign in</Link></p></section></main>;
}

export function ResetPasswordForm({ token }: { token: string }) {
  const [password, setPassword] = useState(""); const [confirmPassword, setConfirmPassword] = useState(""); const [code, setCode] = useState(""); const [requiresMfa, setRequiresMfa] = useState(false); const [validated, setValidated] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { let active = true; void fetch("/api/auth/validate-reset", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token }) }).then(async response => { const data = await response.json() as { valid?: boolean; requiresMfa?: boolean; error?: string }; if (!active) return; if (!response.ok || !data.valid) setError(data.error ?? "This reset link is invalid or has expired."); else setRequiresMfa(data.requiresMfa === true); setValidated(true); }).catch(() => { if (active) { setError("Could not validate this reset link. Try again."); setValidated(true); } }); return () => { active = false; }; }, [token]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage(""); setError(""); try { const response = await fetch("/api/auth/reset-password", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token, password, confirmPassword, code: code || undefined }) }); const data = await response.json() as { message?: string; error?: string }; if (!response.ok) { if (/authenticator|recovery code/i.test(data.error ?? "")) setRequiresMfa(true); throw new Error(data.error ?? "Could not reset password."); } setMessage(data.message ?? "Password updated. Sign in again."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not reset password."); } finally { setBusy(false); } }
  return <main className="auth-shell"><section className="auth-card"><p className="eyebrow"><span className="live-dot"/> ACCOUNT RECOVERY</p><h1>Choose a new<br/><span>password.</span></h1><p className="auth-intro">{!validated ? "Checking your secure reset link…" : requiresMfa ? "This account uses two-factor authentication. Verify your identity to continue." : "Choose a strong password you haven’t used for ARCUS before."}</p>{validated && !error && <form className="auth-form" onSubmit={(event) => void submit(event)}><label>New password<input type="password" minLength={10} maxLength={128} autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} required/></label><label>Confirm password<input type="password" minLength={10} maxLength={128} autoComplete="new-password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} required/></label>{requiresMfa && <label>Authenticator or recovery code<input value={code} onChange={(event) => setCode(event.target.value.trim().slice(0, 40))} inputMode="numeric" autoComplete="one-time-code" required/></label>}<button className="action-button auth-submit" disabled={busy}>{busy ? "Updating…" : "Reset password"}</button></form>}{message && <p className="auth-notice" role="status">{message} <Link href="/login">Sign in</Link></p>}{error && <p className="auth-error" role="alert">{error} <Link href="/auth/forgot-password">Request a new link</Link></p>}</section></main>;
}
