import type { Exercise } from "./catalog.ts";
export const EXERCISE_CATEGORIES=["Chest","Back","Shoulders","Biceps","Triceps","Quads","Hamstrings","Glutes","Calves","Abs","Cardio","Olympic","Compound"];
export function exerciseCategory(exercise:Exercise){if(exercise.category)return exercise.category;const muscle=exercise.muscle.toLowerCase();if(["lats","upper back","traps","erectors"].includes(muscle))return "Back";if(muscle.includes("delt"))return "Shoulders";if(muscle.includes("chest"))return "Chest";if(muscle==="obliques")return "Abs";return EXERCISE_CATEGORIES.find(c=>c.toLowerCase()===muscle)??"Compound";}
export function exerciseContent(exercise:Exercise){
  const pattern=exercise.pattern.toLowerCase();
  const instructions=exercise.instructions??(pattern.includes("squat")?"Set your feet in a comfortable stance and brace your trunk. Lower under control through a comfortable range, then push through your feet to stand. Keep each repetition consistent.":pattern.includes("hinge")||pattern.includes("hip extension")?"Brace your trunk and move through your hips with a controlled load. Keep the load close to your body and avoid jerking it into position. Reverse the movement smoothly.":pattern.includes("push")?"Set a stable base and keep your wrists aligned with the load. Press smoothly through a comfortable range, then lower under control. Avoid bouncing at the bottom.":pattern.includes("pull")?"Start from a stable position and draw your elbows toward your body. Keep your trunk steady and return the load slowly. Use a range you can control without swinging.":pattern.includes("curl")||pattern.includes("flexion")?"Stabilize the joints that are not moving. Lift through a comfortable range without swinging, then lower slowly. Choose a load that lets you maintain control.":pattern.includes("cardio")?"Start at an easy pace and increase gradually to a sustainable effort. Keep your movement relaxed and controlled throughout. Use time or repetitions to track your session.":pattern.includes("olympic")?"Practice the movement with a light load and establish a stable starting position. Move the bar close to your body and finish in a balanced receiving position. Learn the technique with qualified coaching before adding load.":"Set up in a stable position and move through a comfortable range of motion. Use a controlled tempo and avoid momentum. Keep your breathing and technique consistent across repetitions.");
  const secondary=exercise.secondaryMuscles??(pattern.includes("push")?["Triceps","Front delts"]:pattern.includes("pull")?["Biceps","Rear delts"]:pattern.includes("squat")?["Glutes","Hamstrings"]:pattern.includes("hinge")?["Glutes","Erectors"]:[]).filter(m=>m!==exercise.muscle);
  return {instructions,primary:exercise.primaryMuscles??[exercise.muscle],secondary};
}
